<?php
/** @var \PersonalizeAI\SocialMedia\Block\FacebookOAuth $block */
?>

<?php if ($block->isLoggedIn() && $block->getModuleStatus()): ?>

 <!-- Container for Facebook OAuth elements -->   
<div id="facebook-oauth-container"> 
    <!-- Button for linking Facebook account -->
    <button id="loginBtn" class="fb-login-button" <?= $block->getFacebookIsLinked() ? 'disabled' : ''; ?>> 
        <i class="ph ph-facebook-logo"></i>
        <?= $block->escapeHtml(__('Link your Facebook')) ?>
    </button>
</div>

<script>
    // Require jQuery and the custom Facebook OAuth js module
    require(['jquery', 'PersonalizeAI_SocialMedia/js/facebook-oauth'], function($, facebookOAuth) {
        
        // Initialize the Facebook OAuth module with the application ID
        facebookOAuth.init('<?= $block->escapeJs($block->getAppId()) ?>'); 
    });
</script>
<hr>
<?php endif; ?>

